pack_id: researched_sample_pack_us_smb
pack_version: 1.0.0

stages:
  - id: S0
    name: Foundations
    headcount_min: 0
    headcount_max: 10
    description: "Founder-led HR admin; minimal formal process."
  - id: S1
    name: Structured Basics
    headcount_min: 11
    headcount_max: 40
    description: "First policies and repeatable onboarding; early manager norms."
  - id: S2
    name: Scaling
    headcount_min: 41
    headcount_max: 100
    description: "Consistency and manager enablement; common inflection for HR ownership."
  - id: S3
    name: Operational Maturity
    headcount_min: 101
    headcount_max: 250
    description: "Repeatable talent systems; reporting and job architecture v1."
  - id: S4
    name: Specialization
    headcount_min: 251
    headcount_max: 500
    description: "Specialized HR roles; operating model and workforce planning."
  - id: S5
    name: Enterprise
    headcount_min: 501
    headcount_max: 999999
    description: "Governance, COEs, service delivery, analytics."

complexity_triggers:
  - id: multi_state
    description: "Employees in 2+ US states"
    stage_bump: 1
    rule: "snapshot.geo.multi_state == true"
  - id: multi_country
    description: "Employees in 2+ countries"
    stage_bump: 2
    rule: "snapshot.geo.multi_country == true"
  - id: regulated
    description: "Regulated environment"
    stage_bump: 1
    rule: "snapshot.company.regulated == true"
  - id: high_growth
    description: "High hiring velocity or growth"
    stage_bump: 1
    rule: "snapshot.growth.high_growth == true"
  - id: contractor_heavy
    description: "Contractors > 25%"
    stage_bump: 1
    rule: "snapshot.workforce.contractor_heavy == true"

weights:
  compliance: 3.0
  business_impact: 2.0
  urgency: 1.5
  confidence_penalty: 2.0

report_template:
  sections: ["stage_summary","top_growth_areas","risk_register","plan_30_60_90","unknowns","appendix"]
  tone: "practical"
  disclaimer: "This report is not legal advice. Consider reviewing compliance topics with counsel and/or your payroll/benefits advisor."

checks:
  - id: C001
    area: "Compliance & policies"
    applies_at_stages: ["S1", "S2", "S3"]
    severity: "High"
    trigger: "Handbook/policy index not found"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Handbook OR policy index OR policy folder link"]
    recommended_next_steps:
      - "Draft handbook v1 core policies"
      - "publish + acknowledgement"
      - "set annual review cadence"
    metrics_to_track: ["Policy ack %"]
    follow_up_questions:
      - "Do you have a handbook draft or policy folder?"
  - id: C002
    area: "Compliance & policies"
    applies_at_stages: ["S0", "S1", "S2", "S3"]
    severity: "High"
    trigger: "I-9 process not described / owner unclear"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["I-9 checklist + retention process"]
    recommended_next_steps:
      - "Assign owner"
      - "document I-9 workflow"
      - "ensure timely completion and retention"
    metrics_to_track: ["I-9 completion timeliness"]
    follow_up_questions:
      - "Who completes I-9s and where are they stored?"
  - id: C003
    area: "Compliance & policies"
    applies_at_stages: ["S2", "S3"]
    severity: "High"
    trigger: "50+ employee threshold prompts not addressed (FMLA/ACA awareness)"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Documented compliance review cadence or external partner confirmation"]
    recommended_next_steps:
      - "Create annual compliance calendar"
      - "confirm coverage obligations with counsel/CPA"
      - "document responsibilities"
    metrics_to_track: ["Compliance calendar completion"]
    follow_up_questions:
      - "Has someone reviewed FMLA/ACA obligations for your situation?"
  - id: C004
    area: "Compliance & policies"
    applies_at_stages: ["S3", "S4", "S5"]
    severity: "Med"
    trigger: "EEO-1 reporting awareness not mentioned at 100+"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["EEO-1 process owner + data pull method"]
    recommended_next_steps:
      - "Assign owner"
      - "validate HRIS data"
      - "prepare annual submission workflow"
    metrics_to_track: ["EEO-1 readiness checklist"]
    follow_up_questions:
      - "Do you currently file EEO-1 or qualify as a federal contractor?"
  - id: C005
    area: "Compliance & policies"
    applies_at_stages: ["S1", "S2", "S3"]
    severity: "Med"
    trigger: "Complaint reporting path not clear"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Policy describing how to report concerns"]
    recommended_next_steps:
      - "Publish reporting channels"
      - "train managers on escalation and documentation"
    metrics_to_track: ["# of reports; time to response"]
    follow_up_questions:
      - "How do employees report concerns today?"
  - id: C006
    area: "Compliance & policies"
    applies_at_stages: ["S2", "S3"]
    severity: "Med"
    trigger: "Investigation/discipline process not documented"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["ER playbook / investigation template"]
    recommended_next_steps:
      - "Create investigation notes template"
      - "define decision owners"
      - "store case notes securely"
    metrics_to_track: ["ER cases logged %"]
    follow_up_questions:
      - "Do you have a standard investigation template?"
  - id: C007
    area: "Hiring & recruiting"
    applies_at_stages: ["S0", "S1", "S2", "S3"]
    severity: "High"
    trigger: "Role scorecards not used"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Scorecard template in use"]
    recommended_next_steps:
      - "Create scorecard per role"
      - "align hiring panel"
      - "require structured debrief"
    metrics_to_track: ["Offer acceptance rate; time-to-fill"]
    follow_up_questions:
      - "Do you use interview scorecards today?"
  - id: C008
    area: "Hiring & recruiting"
    applies_at_stages: ["S1", "S2", "S3"]
    severity: "Med"
    trigger: "Interview process inconsistent across teams"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Documented interview loop + debrief template"]
    recommended_next_steps:
      - "Standardize interview loop"
      - "define competencies"
      - "train interviewers"
    metrics_to_track: ["Candidate NPS"]
    follow_up_questions:
      - "How are interviews run and debriefed?"
  - id: C009
    area: "Hiring & recruiting"
    applies_at_stages: ["S2", "S3"]
    severity: "Med"
    trigger: "No recruiting funnel metrics tracked"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Basic funnel tracking (source → screen → onsite → offer)"]
    recommended_next_steps:
      - "Start weekly funnel reporting"
      - "identify bottlenecks"
      - "fix top 1 constraint"
    metrics_to_track: ["Conversion rates; time-in-stage"]
    follow_up_questions:
      - "Do you track funnel stages anywhere?"
  - id: C010
    area: "Hiring & recruiting"
    applies_at_stages: ["S2", "S3"]
    severity: "Med"
    trigger: "Offer process lacks approvals / comp guardrails"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Offer approval workflow + ranges/bands"]
    recommended_next_steps:
      - "Define offer approvals"
      - "create comp guardrails"
      - "reduce renegotiation churn"
    metrics_to_track: ["Offer cycle time"]
    follow_up_questions:
      - "Who approves offers and comp today?"
  - id: C011
    area: "Onboarding"
    applies_at_stages: ["S0", "S1", "S2", "S3"]
    severity: "High"
    trigger: "Onboarding checklist not found"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Checklist + owners + preboarding items"]
    recommended_next_steps:
      - "Create checklist"
      - "assign owners"
      - "include IT provisioning"
      - "schedule key meetings"
    metrics_to_track: ["Time-to-productivity; 0-90 day attrition"]
    follow_up_questions:
      - "Do you have a standard onboarding checklist?"
  - id: C012
    area: "Onboarding"
    applies_at_stages: ["S1", "S2", "S3"]
    severity: "Med"
    trigger: "No 30/60/90 expectations for new hires"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Role-based 30/60/90 plan template"]
    recommended_next_steps:
      - "Create role-based 30/60/90 templates"
      - "manager review at 2 and 6 weeks"
    metrics_to_track: ["Manager satisfaction; ramp milestones"]
    follow_up_questions:
      - "Do managers set ramp expectations?"
  - id: C013
    area: "Onboarding"
    applies_at_stages: ["S2", "S3"]
    severity: "Med"
    trigger: "No onboarding feedback loop"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Survey or check-ins at 30/60/90"]
    recommended_next_steps:
      - "Implement new-hire check-ins"
      - "track themes"
      - "iterate onboarding"
    metrics_to_track: ["New-hire survey score"]
    follow_up_questions:
      - "Do you survey/check-in with new hires?"
  - id: C014
    area: "Manager enablement"
    applies_at_stages: ["S1", "S2", "S3"]
    severity: "High"
    trigger: "Managers lack guidance on feedback/documentation"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Manager expectations doc + training"]
    recommended_next_steps:
      - "Create manager basics guide"
      - "train on feedback and documentation"
      - "run office hours"
    metrics_to_track: ["Manager 1:1 adherence"]
    follow_up_questions:
      - "Do you provide manager training?"
  - id: C015
    area: "Manager enablement"
    applies_at_stages: ["S2", "S3"]
    severity: "Med"
    trigger: "Manager onboarding not defined"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Manager onboarding checklist"]
    recommended_next_steps:
      - "Define manager onboarding"
      - "include HR processes + coaching skills"
    metrics_to_track: ["New manager confidence score"]
    follow_up_questions:
      - "How do new managers learn expectations?"
  - id: C016
    area: "Performance & feedback"
    applies_at_stages: ["S0", "S1"]
    severity: "Med"
    trigger: "Goals/feedback cadence not explicit"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Monthly/quarterly check-in template"]
    recommended_next_steps:
      - "Set quarterly goals"
      - "require monthly check-ins"
      - "use simple template"
    metrics_to_track: ["Goal completion"]
    follow_up_questions:
      - "How often do managers do 1:1s?"
  - id: C017
    area: "Performance & feedback"
    applies_at_stages: ["S2", "S3"]
    severity: "High"
    trigger: "No structured performance cycle"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Documented cycle + calibration-lite"]
    recommended_next_steps:
      - "Implement 2x/year cycle"
      - "define ratings or narratives"
      - "run calibration"
    metrics_to_track: ["Performance completion %"]
    follow_up_questions:
      - "Do you run formal reviews?"
  - id: C018
    area: "Performance & feedback"
    applies_at_stages: ["S3"]
    severity: "Med"
    trigger: "No PIP/underperformance workflow"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["PIP template + legal review guidance"]
    recommended_next_steps:
      - "Create workflow"
      - "align on documentation"
      - "ensure consistent application"
    metrics_to_track: ["PIP outcomes"]
    follow_up_questions:
      - "How do you handle underperformance today?"
  - id: C019
    area: "Comp & leveling"
    applies_at_stages: ["S1", "S2", "S3"]
    severity: "High"
    trigger: "No salary ranges/bands for common roles"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Bands/ranges doc + update cadence"]
    recommended_next_steps:
      - "Create ranges for top roles"
      - "define offer guardrails"
      - "review annually"
    metrics_to_track: ["Offer exceptions"]
    follow_up_questions:
      - "Do you have salary ranges?"
  - id: C020
    area: "Comp & leveling"
    applies_at_stages: ["S2", "S3"]
    severity: "Med"
    trigger: "Leveling/career expectations unclear"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Leveling doc for core functions"]
    recommended_next_steps:
      - "Draft lightweight leveling"
      - "link to promotion criteria"
      - "socialize with managers"
    metrics_to_track: ["Promotion clarity survey"]
    follow_up_questions:
      - "Do employees ask about promotion expectations?"
  - id: C021
    area: "Systems & data"
    applies_at_stages: ["S1", "S2", "S3"]
    severity: "Med"
    trigger: "Employee data is scattered (spreadsheets + email)"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Single source of truth (HRIS or disciplined sheet)"]
    recommended_next_steps:
      - "Define data owner"
      - "standardize fields"
      - "create employee directory"
    metrics_to_track: ["Data completeness %"]
    follow_up_questions:
      - "Where do you store employee records?"
  - id: C022
    area: "Systems & data"
    applies_at_stages: ["S2", "S3"]
    severity: "Med"
    trigger: "HRIS not implemented by scaling stage"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["HRIS implemented or selection plan"]
    recommended_next_steps:
      - "Select HRIS"
      - "map workflows"
      - "migrate data"
      - "train admins"
    metrics_to_track: ["HRIS adoption rate"]
    follow_up_questions:
      - "Are you on an HRIS today?"
  - id: C023
    area: "Systems & data"
    applies_at_stages: ["S2", "S3"]
    severity: "Low"
    trigger: "No ticketing/case tracking for HR requests"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Inbox triage process or ticket tool"]
    recommended_next_steps:
      - "Set intake channel"
      - "define SLA"
      - "track recurring issues"
    metrics_to_track: ["Time to response"]
    follow_up_questions:
      - "How do employees request HR help?"
  - id: C024
    area: "Retention/ER/engagement"
    applies_at_stages: ["S1", "S2", "S3"]
    severity: "Med"
    trigger: "No exit interview process/themes"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Exit template + themes log"]
    recommended_next_steps:
      - "Standardize exits"
      - "track themes quarterly"
      - "link actions to themes"
    metrics_to_track: ["Exit completion %"]
    follow_up_questions:
      - "Do you do exit interviews?"
  - id: C025
    area: "Retention/ER/engagement"
    applies_at_stages: ["S2", "S3"]
    severity: "Med"
    trigger: "High early attrition not analyzed"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Cohort analysis + root causes"]
    recommended_next_steps:
      - "Segment early churn"
      - "fix top drivers"
      - "improve onboarding/role clarity"
    metrics_to_track: ["0-90 day attrition"]
    follow_up_questions:
      - "What’s 0–90 day attrition?"
  - id: C026
    area: "Retention/ER/engagement"
    applies_at_stages: ["S2", "S3"]
    severity: "Low"
    trigger: "No engagement pulse cadence"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Pulse survey or structured check-ins"]
    recommended_next_steps:
      - "Run quarterly pulse"
      - "managers action plan top themes"
    metrics_to_track: ["Engagement score"]
    follow_up_questions:
      - "Do you run any engagement survey?"
  - id: C027
    area: "Org design"
    applies_at_stages: ["S2", "S3"]
    severity: "Med"
    trigger: "Spans/layers unclear; role overlap"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Org chart + role clarity docs"]
    recommended_next_steps:
      - "Clarify ownership"
      - "create RACI for top workflows"
      - "adjust manager loads"
    metrics_to_track: ["Manager span distribution"]
    follow_up_questions:
      - "Do you have an org chart / clear ownership?"
  - id: C028
    area: "Benefits"
    applies_at_stages: ["S1", "S2", "S3"]
    severity: "Low"
    trigger: "Benefits communication unclear"
    rule: ""  # TODO: map triggers to snapshot fields (engine-specific)
    evidence_passes: ["Benefits overview doc"]
    recommended_next_steps:
      - "Create benefits one-pager"
      - "onboarding benefits walkthrough"
    metrics_to_track: ["Benefits questions volume"]
    follow_up_questions:
      - "Do employees understand benefits enrollment?"
